### ISSUE TITLE
Failed to pull singularity image

### ISSUE THREAD

**Issue by xuemeiluo** [bcgsc/TMBur#1]
I was trying to run the tool, but the job failed to pull singularity image. I was wondering if the container path is correct?

container = 'library://richardcorbett/profyle_tmb/profyle_tmb:v0_4_0'

Thanks.

**Comment by RichardCorbett** [comment]
Hi there, Can you share the error you are getting?   Usually this error happens either when either the command is run on a machine that can't see the internet, or when there is an outage at the singularity servers.   I just tried 
`singularity pull library://richardcorbett/profyle_tmb/profyle_tmb:v0_4_0` on my machine and it worked, so I expect the issue is with connectivity from your server.

**Comment by xuemeiluo** [comment]
Hello, I am running the command on a node which has internet connection. Here is the error message:

Pulling Singularity image library://richardcorbett/profyle_tmb/profyle_tmb:v0_4_0 [cache /.mounts/labs/prod/scratch/xluo/TMBur/work/singularity/richardcorbett-profyle_tmb-profyle_tmb-v0_4_0.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /.mounts/labs/prod/scratch/xluo/TMBur/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'copy_reference (/reference/hs37d5.fa)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name richardcorbett-profyle_tmb-profyle_tmb-v0_4_0.img.pulling.1642107744667 library://richardcorbett/profyle_tmb/profyle_tmb:v0_4_0 > /dev/null
  status : 127
  message:
    bash: singularity: command not found

**Comment by RichardCorbett** [comment]
Ah I see.

You need to have singularity installed on your system for this pipeline to work.     I'll add that to the README.

**Comment by xuemeiluo** [comment]
ok, thanks.

**Comment by RichardCorbett** [comment]
OK thanks.  I appreciate you trying to run this.
